---
- hosts: dev
  become: True
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: Start docker service
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present

    - name: Start the container backend-1
      docker_container:
        name: backend-1
        image: "lucasmocerinomonteiro/payshare-backend:{{DOCKER_TAG}}"
        state: started
        restart_policy: always
        env: 
            SPRING_DATASOURCE_URL: {{SPRING_DATASOURCE_URL}}
            SPRING_DATASOURCE_USERNAME: {{POSTGRES_USERNAME}}
            SPRING_DATASOURCE_PASSWORD: {{POSTGRES_PASSWORD}}
        published_ports:
          - 0.0.0.0:8080:8080

    - name: Start the container backend-2
      docker_container:
        name: backend-2
        image: "lucasmocerinomonteiro/payshare-backend:{{DOCKER_TAG}}"
        state: started
        restart_policy: always
        env: 
            SPRING_DATASOURCE_URL: {{SPRING_DATASOURCE_URL}}
            SPRING_DATASOURCE_USERNAME: {{POSTGRES_USERNAME}}
            SPRING_DATASOURCE_PASSWORD: {{POSTGRES_PASSWORD}}
        published_ports:
          - 0.0.0.0:8081:8080

    - name: Start the container postgres
      docker_container:
        name: db
        image: "postgres:13.1-alpine"
        state: started
        restart_policy: always
          env:
              POSTGRES_USER: {{POSTGRES_USERNAME}}
              POSTGRES_PASSWORD: {{POSTGRES_PASSWORD}}
        published_ports:
          - 0.0.0.0:5432:5432
