pipeline { 
    environment { 
        registry = "lucasmocerinomonteiro/payshare-backend" 
        registryCredential = 'id_docker_hub' 
        dockerImage = '' 
    }
    agent any 
    stages { 
        stage('Building Docker Image') { 
            steps { 
                script { 
                    dockerImage = docker.build registry + ":$BUILD_NUMBER" 
                }
            } 
        }
        stage('Push Image to Registry Docker HUB') { 
            steps { 
                script { 
                docker.withRegistry( '', registryCredential ) { 
                        dockerImage.push() 
                    }
                } 
            }
        } 
        stage('Cleaning up') { 
            steps { 
                sh "docker rmi $registry:$BUILD_NUMBER" 
            }
        }
        stage('Docker deploy to Dev') { 
            steps { 
                 ansiblePlaybook credentialsId: 'ec2-dev-web', disableHostKeyChecking: true, extras: "-e DOCKER_TAG=${BUILD_NUMBER} -e SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/payshare -e POSTGRES_BASE=payshare -e POSTGRES_USERNAME=payshare -e POSTGRES_PASSWORD=payshare -e POSTGRES_PORT=5432", installation: 'ansible',  inventory: 'cd/env/hosts', playbook: 'cd/site.yml'
            }
        } 
    }
}
